const path = require('node:path');
const fs = require('node:fs');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');
const { build } = require('esbuild');

async function buildOffline() {
  const root = __dirname;
  fs.mkdirSync(path.join(root, 'assets/ui'), { recursive: true });
  const cli = path.join(path.dirname(require.resolve('@tailwindcss/cli/package.json')), 'dist/index.mjs');
  execFileSync(process.execPath, [cli, '-i', 'styles/offline-page.css', '-o', 'assets/ui/offline-page.css', '--minify'], { cwd: root, stdio: 'inherit' });
  await build({
    absWorkingDir: root, entryPoints: ['components/offline-page.tsx'], outfile: 'assets/ui/offline-page.js',
    bundle: true, minify: true, format: 'esm', platform: 'browser', target: ['es2020'], jsx: 'automatic',
    define: { 'process.env.NODE_ENV': '"production"' }, legalComments: 'eof',
  });
  await build({
    absWorkingDir: root, entryPoints: ['lib/offline-batman.js'], outfile: 'assets/ui/offline-batman.js',
    bundle: true, minify: true, format: 'esm', platform: 'browser', target: ['es2020'], legalComments: 'eof',
  });
  const assets = ['/offline.html', '/offline-boot.js', '/assets/ui/offline-page.css', '/assets/ui/offline-page.js',
    '/assets/ui/offline-batman.js', '/assets/batman/cursor.svg', '/assets/fonts/inter-latin.woff2', '/assets/fonts/lilita-one-latin.woff2', '/assets/brand/favicon.svg'];
  const hash = crypto.createHash('sha256');
  for (const asset of assets) hash.update(fs.readFileSync(path.join(root, asset.slice(1))));
  const template = fs.readFileSync(path.join(root, 'lib/offline-worker.js'), 'utf8');
  hash.update(template);
  fs.writeFileSync(path.join(root, 'offline-sw.js'), `// Generated by build-offline.cjs.\nconst CACHE_NAME = 'shub-offline-${hash.digest('hex').slice(0, 12)}';\nconst OFFLINE_ASSETS = ${JSON.stringify(assets)};\n${template}`);
  console.log('Offline Batman page and service worker compiled.');
}
module.exports = buildOffline;
if (require.main === module) buildOffline().catch(error => { console.error(error); process.exitCode = 1; });
