// Artwork sources are recorded per item. Cards are exactly 4:3.
export const gamingImages = [
  {
    "type": "image",
    "title": "Batman: Arkham Knight",
    "alt": "Batman: Arkham Knight game artwork",
    "src": "assets/gaming/batman-arkham-knight-480.webp",
    "srcset": "assets/gaming/batman-arkham-knight-480.webp 480w, assets/gaming/batman-arkham-knight-960.webp 960w",
    "original": "assets/gaming/batman-arkham-knight-960.webp",
    "sourceOriginal": "assets/gaming/batman-arkham-knight-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/208650/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/208650/"
  },
  {
    "type": "image",
    "title": "God of War Ragnarök",
    "alt": "God of War Ragnarök game artwork",
    "src": "assets/gaming/god-of-war-ragnarok-480.webp",
    "srcset": "assets/gaming/god-of-war-ragnarok-480.webp 480w, assets/gaming/god-of-war-ragnarok-960.webp 960w",
    "original": "assets/gaming/god-of-war-ragnarok-960.webp",
    "sourceOriginal": "assets/gaming/god-of-war-ragnarok-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2322010/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/2322010/"
  },
  {
    "type": "image",
    "title": "Battlefield 4",
    "alt": "Battlefield 4 game artwork",
    "src": "assets/gaming/battlefield-4-480.webp",
    "srcset": "assets/gaming/battlefield-4-480.webp 480w, assets/gaming/battlefield-4-960.webp 960w",
    "original": "assets/gaming/battlefield-4-960.webp",
    "sourceOriginal": "assets/gaming/battlefield-4-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238860/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1238860/"
  },
  {
    "type": "image",
    "title": "Ghost of Tsushima DIRECTOR'S CUT",
    "alt": "Ghost of Tsushima DIRECTOR'S CUT game artwork",
    "src": "assets/gaming/ghost-of-tsushima-480.webp",
    "srcset": "assets/gaming/ghost-of-tsushima-480.webp 480w, assets/gaming/ghost-of-tsushima-960.webp 960w",
    "original": "assets/gaming/ghost-of-tsushima-960.webp",
    "sourceOriginal": "assets/gaming/ghost-of-tsushima-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2215430/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/2215430/"
  },
  {
    "type": "image",
    "title": "ELDEN RING",
    "alt": "ELDEN RING game artwork",
    "src": "assets/gaming/elden-ring-480.webp",
    "srcset": "assets/gaming/elden-ring-480.webp 480w, assets/gaming/elden-ring-960.webp 960w",
    "original": "assets/gaming/elden-ring-960.webp",
    "sourceOriginal": "assets/gaming/elden-ring-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1245620/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1245620/"
  },
  {
    "type": "image",
    "title": "Marvel's Spider-Man 2",
    "alt": "Marvel's Spider-Man 2 game artwork",
    "src": "assets/gaming/marvel-spider-man-2-480.webp",
    "srcset": "assets/gaming/marvel-spider-man-2-480.webp 480w, assets/gaming/marvel-spider-man-2-960.webp 960w",
    "original": "assets/gaming/marvel-spider-man-2-960.webp",
    "sourceOriginal": "assets/gaming/marvel-spider-man-2-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2651280/library_600x900_2x.jpg",
    "sourcePage": "https://store.steampowered.com/app/2651280/"
  },
  {
    "type": "image",
    "title": "Watch_Dogs",
    "alt": "Watch_Dogs game artwork",
    "src": "assets/gaming/watch-dogs-480.webp",
    "srcset": "assets/gaming/watch-dogs-480.webp 480w, assets/gaming/watch-dogs-960.webp 960w",
    "original": "assets/gaming/watch-dogs-960.webp",
    "sourceOriginal": "assets/gaming/watch-dogs-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/243470/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/243470/"
  },
  {
    "type": "image",
    "title": "Ghost of Yōtei",
    "alt": "Ghost of Yōtei game artwork",
    "src": "assets/gaming/ghost-of-yotei-480.webp",
    "srcset": "assets/gaming/ghost-of-yotei-480.webp 480w, assets/gaming/ghost-of-yotei-960.webp 960w",
    "original": "assets/gaming/ghost-of-yotei-960.webp",
    "sourceOriginal": "assets/gaming/ghost-of-yotei-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://image.api.playstation.com/vulcan/ap/rnd/202607/2723/890df32c227f619c5bd80e9f34ba2be53d0fea4b1615adee.png",
    "sourcePage": "https://www.playstation.com/en-us/games/ghost-of-yotei/"
  },
  {
    "type": "image",
    "title": "SILENT HILL 2",
    "alt": "SILENT HILL 2 game artwork",
    "src": "assets/gaming/silent-hill-2-480.webp",
    "srcset": "assets/gaming/silent-hill-2-480.webp 480w, assets/gaming/silent-hill-2-960.webp 960w",
    "original": "assets/gaming/silent-hill-2-960.webp",
    "sourceOriginal": "assets/gaming/silent-hill-2-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2124490/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/2124490/"
  },
  {
    "type": "image",
    "title": "Red Dead Redemption 2",
    "alt": "Red Dead Redemption 2 game artwork",
    "src": "assets/gaming/red-dead-redemption-2-480.webp",
    "srcset": "assets/gaming/red-dead-redemption-2-480.webp 480w, assets/gaming/red-dead-redemption-2-960.webp 960w",
    "original": "assets/gaming/red-dead-redemption-2-960.webp",
    "sourceOriginal": "assets/gaming/red-dead-redemption-2-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1174180/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1174180/"
  },
  {
    "type": "image",
    "title": "007 First Light",
    "alt": "007 First Light game artwork",
    "src": "assets/gaming/007-first-light-480.webp",
    "srcset": "assets/gaming/007-first-light-480.webp 480w, assets/gaming/007-first-light-960.webp 960w",
    "original": "assets/gaming/007-first-light-960.webp",
    "sourceOriginal": "assets/gaming/007-first-light-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://image.api.playstation.com/vulcan/ap/rnd/202607/2312/ecb14ee33763d4dd295dbb4f4207f9961bf3dcd8ea3bba9f.png",
    "sourcePage": "https://www.playstation.com/en-us/games/007-first-light/"
  },
  {
    "type": "image",
    "title": "Resident Evil 7 Biohazard",
    "alt": "Resident Evil 7 Biohazard game artwork",
    "src": "assets/gaming/resident-evil-7-480.webp",
    "srcset": "assets/gaming/resident-evil-7-480.webp 480w, assets/gaming/resident-evil-7-960.webp 960w",
    "original": "assets/gaming/resident-evil-7-960.webp",
    "sourceOriginal": "assets/gaming/resident-evil-7-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/418370/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/418370/"
  },
  {
    "type": "image",
    "title": "Resident Evil Village",
    "alt": "Resident Evil Village game artwork",
    "src": "assets/gaming/resident-evil-village-480.webp",
    "srcset": "assets/gaming/resident-evil-village-480.webp 480w, assets/gaming/resident-evil-village-960.webp 960w",
    "original": "assets/gaming/resident-evil-village-960.webp",
    "sourceOriginal": "assets/gaming/resident-evil-village-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1196590/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1196590/"
  },
  {
    "type": "image",
    "title": "Assassin's Creed Origins",
    "alt": "Assassin's Creed Origins game artwork",
    "src": "assets/gaming/assassins-creed-origins-480.webp",
    "srcset": "assets/gaming/assassins-creed-origins-480.webp 480w, assets/gaming/assassins-creed-origins-960.webp 960w",
    "original": "assets/gaming/assassins-creed-origins-960.webp",
    "sourceOriginal": "assets/gaming/assassins-creed-origins-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/582160/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/582160/"
  },
  {
    "type": "image",
    "title": "TEKKEN 8",
    "alt": "TEKKEN 8 game artwork",
    "src": "assets/gaming/tekken-8-480.webp",
    "srcset": "assets/gaming/tekken-8-480.webp 480w, assets/gaming/tekken-8-960.webp 960w",
    "original": "assets/gaming/tekken-8-960.webp",
    "sourceOriginal": "assets/gaming/tekken-8-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1778820/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1778820/"
  },
  {
    "type": "image",
    "title": "Mortal Kombat XL",
    "alt": "Mortal Kombat XL game artwork",
    "src": "assets/gaming/mortal-kombat-x-480.webp",
    "srcset": "assets/gaming/mortal-kombat-x-480.webp 480w, assets/gaming/mortal-kombat-x-960.webp 960w",
    "original": "assets/gaming/mortal-kombat-x-960.webp",
    "sourceOriginal": "assets/gaming/mortal-kombat-x-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://image.api.playstation.com/cdn/UP1018/CUSA03589_00/ezdXAsaNqjRSG19ujCjT1p1KqoI67wDO.png",
    "sourcePage": "https://store.playstation.com/en-us/product/UP1018-CUSA03589_00-MORTALKOMBATXL00/"
  },
  {
    "type": "image",
    "title": "Valorant",
    "alt": "Valorant game artwork",
    "src": "assets/gaming/valorant-480.webp",
    "srcset": "assets/gaming/valorant-480.webp 480w, assets/gaming/valorant-960.webp 960w",
    "original": "assets/gaming/valorant-960.webp",
    "sourceOriginal": "assets/gaming/valorant-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://image.api.playstation.com/vulcan/ap/rnd/202609/0921/8b9042708110602ee93c3a28f4efee0aba91c4b9419fa128.png",
    "sourcePage": "https://www.playstation.com/en-us/games/valorant/"
  },
  {
    "type": "image",
    "title": "Call of Duty: Modern Warfare",
    "alt": "Call of Duty: Modern Warfare game artwork",
    "src": "assets/gaming/call-of-duty-modern-warfare-480.webp",
    "srcset": "assets/gaming/call-of-duty-modern-warfare-480.webp 480w, assets/gaming/call-of-duty-modern-warfare-960.webp 960w",
    "original": "assets/gaming/call-of-duty-modern-warfare-960.webp",
    "sourceOriginal": "assets/gaming/call-of-duty-modern-warfare-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2000950/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/2000950/"
  },
  {
    "type": "image",
    "title": "The Last of Us Part I",
    "alt": "The Last of Us Part I game artwork",
    "src": "assets/gaming/the-last-of-us-part-i-480.webp",
    "srcset": "assets/gaming/the-last-of-us-part-i-480.webp 480w, assets/gaming/the-last-of-us-part-i-960.webp 960w",
    "original": "assets/gaming/the-last-of-us-part-i-960.webp",
    "sourceOriginal": "assets/gaming/the-last-of-us-part-i-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1888930/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1888930/"
  },
  {
    "type": "image",
    "title": "PRAGMATA",
    "alt": "PRAGMATA game artwork",
    "src": "assets/gaming/pragmata-480.webp",
    "srcset": "assets/gaming/pragmata-480.webp 480w, assets/gaming/pragmata-960.webp 960w",
    "original": "assets/gaming/pragmata-960.webp",
    "sourceOriginal": "assets/gaming/pragmata-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3357650/e32e168b25ed68a0cf6264c220c07e96c2abfb56/header.jpg?t=1789603448",
    "sourcePage": "https://store.steampowered.com/app/3357650/"
  },
  {
    "type": "image",
    "title": "Need for Speed: Most Wanted (2005)",
    "alt": "Need for Speed: Most Wanted (2005) game artwork",
    "src": "assets/gaming/need-for-speed-most-wanted-480.webp",
    "srcset": "assets/gaming/need-for-speed-most-wanted-480.webp 480w, assets/gaming/need-for-speed-most-wanted-960.webp 960w",
    "original": "assets/gaming/need-for-speed-most-wanted-960.webp",
    "sourceOriginal": "assets/gaming/need-for-speed-most-wanted-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://images.launchbox-app.com/0789b478-dee4-4fbd-b814-097da28ce33d.jpg",
    "sourcePage": "https://gamesdb.launchbox-app.com/games/images/5015-need-for-speed-most-wanted-2005"
  },
  {
    "type": "image",
    "title": "The Witcher 3: Wild Hunt — Remastered",
    "alt": "The Witcher 3: Wild Hunt — Remastered game artwork",
    "src": "assets/gaming/the-witcher-3-480.webp",
    "srcset": "assets/gaming/the-witcher-3-480.webp 480w, assets/gaming/the-witcher-3-960.webp 960w",
    "original": "assets/gaming/the-witcher-3-960.webp",
    "sourceOriginal": "assets/gaming/the-witcher-3-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/292030/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/292030/"
  },
  {
    "type": "image",
    "title": "Mass Effect 3 N7 Digital Deluxe Edition (2012)",
    "alt": "Mass Effect 3 N7 Digital Deluxe Edition (2012) game artwork",
    "src": "assets/gaming/mass-effect-3-480.webp",
    "srcset": "assets/gaming/mass-effect-3-480.webp 480w, assets/gaming/mass-effect-3-960.webp 960w",
    "original": "assets/gaming/mass-effect-3-960.webp",
    "sourceOriginal": "assets/gaming/mass-effect-3-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1238020/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1238020/"
  },
  {
    "type": "image",
    "title": "DARK SOULS III",
    "alt": "DARK SOULS III game artwork",
    "src": "assets/gaming/dark-souls-iii-480.webp",
    "srcset": "assets/gaming/dark-souls-iii-480.webp 480w, assets/gaming/dark-souls-iii-960.webp 960w",
    "original": "assets/gaming/dark-souls-iii-960.webp",
    "sourceOriginal": "assets/gaming/dark-souls-iii-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/374320/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/374320/"
  },
  {
    "type": "image",
    "title": "Detroit: Become Human",
    "alt": "Detroit: Become Human game artwork",
    "src": "assets/gaming/detroit-become-human-480.webp",
    "srcset": "assets/gaming/detroit-become-human-480.webp 480w, assets/gaming/detroit-become-human-960.webp 960w",
    "original": "assets/gaming/detroit-become-human-960.webp",
    "sourceOriginal": "assets/gaming/detroit-become-human-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1222140/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1222140/"
  },
  {
    "type": "image",
    "title": "METAL GEAR SOLID V: THE PHANTOM PAIN",
    "alt": "METAL GEAR SOLID V: THE PHANTOM PAIN game artwork",
    "src": "assets/gaming/metal-gear-solid-v-the-phantom-pain-480.webp",
    "srcset": "assets/gaming/metal-gear-solid-v-the-phantom-pain-480.webp 480w, assets/gaming/metal-gear-solid-v-the-phantom-pain-960.webp 960w",
    "original": "assets/gaming/metal-gear-solid-v-the-phantom-pain-960.webp",
    "sourceOriginal": "assets/gaming/metal-gear-solid-v-the-phantom-pain-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/287700/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/287700/"
  },
  {
    "type": "image",
    "title": "Far Cry 5",
    "alt": "Far Cry 5 game artwork",
    "src": "assets/gaming/far-cry-5-480.webp",
    "srcset": "assets/gaming/far-cry-5-480.webp 480w, assets/gaming/far-cry-5-960.webp 960w",
    "original": "assets/gaming/far-cry-5-960.webp",
    "sourceOriginal": "assets/gaming/far-cry-5-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/552520/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/552520/"
  },
  {
    "type": "image",
    "title": "Forza Horizon 5",
    "alt": "Forza Horizon 5 game artwork",
    "src": "assets/gaming/forza-horizon-5-480.webp",
    "srcset": "assets/gaming/forza-horizon-5-480.webp 480w, assets/gaming/forza-horizon-5-960.webp 960w",
    "original": "assets/gaming/forza-horizon-5-960.webp",
    "sourceOriginal": "assets/gaming/forza-horizon-5-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1551360/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1551360/"
  },
  {
    "type": "image",
    "title": "Grand Theft Auto V Enhanced",
    "alt": "Grand Theft Auto V Enhanced game artwork",
    "src": "assets/gaming/grand-theft-auto-v-480.webp",
    "srcset": "assets/gaming/grand-theft-auto-v-480.webp 480w, assets/gaming/grand-theft-auto-v-960.webp 960w",
    "original": "assets/gaming/grand-theft-auto-v-960.webp",
    "sourceOriginal": "assets/gaming/grand-theft-auto-v-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/3240220/library_600x900_2x.jpg",
    "sourcePage": "https://store.steampowered.com/app/3240220/"
  },
  {
    "type": "image",
    "title": "Black Myth: Wukong",
    "alt": "Black Myth: Wukong game artwork",
    "src": "assets/gaming/black-myth-wukong-480.webp",
    "srcset": "assets/gaming/black-myth-wukong-480.webp 480w, assets/gaming/black-myth-wukong-960.webp 960w",
    "original": "assets/gaming/black-myth-wukong-960.webp",
    "sourceOriginal": "assets/gaming/black-myth-wukong-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/2358720/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/2358720/"
  },
  {
    "type": "image",
    "title": "Uncharted 4: A Thief’s End",
    "alt": "Uncharted 4: A Thief’s End game artwork",
    "src": "assets/gaming/uncharted-480.webp",
    "srcset": "assets/gaming/uncharted-480.webp 480w, assets/gaming/uncharted-960.webp 960w",
    "original": "assets/gaming/uncharted-960.webp",
    "sourceOriginal": "assets/gaming/uncharted-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://image.api.playstation.com/vulcan/img/rnd/202011/1018/SGqMZHd7WWmN4XIcLfYMxJsc.png",
    "sourcePage": "https://www.playstation.com/en-us/games/uncharted-4-a-thiefs-end/"
  },
  {
    "type": "image",
    "title": "HITMAN World of Assassination",
    "alt": "HITMAN World of Assassination game artwork",
    "src": "assets/gaming/hitman-world-of-assassination-480.webp",
    "srcset": "assets/gaming/hitman-world-of-assassination-480.webp 480w, assets/gaming/hitman-world-of-assassination-960.webp 960w",
    "original": "assets/gaming/hitman-world-of-assassination-960.webp",
    "sourceOriginal": "assets/gaming/hitman-world-of-assassination-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://shared.akamai.steamstatic.com/store_item_assets/steam/apps/1659040/capsule_616x353.jpg",
    "sourcePage": "https://store.steampowered.com/app/1659040/"
  },
  {
    "type": "image",
    "title": "Minecraft",
    "alt": "Minecraft game artwork",
    "src": "assets/gaming/minecraft-480.webp",
    "srcset": "assets/gaming/minecraft-480.webp 480w, assets/gaming/minecraft-960.webp 960w",
    "original": "assets/gaming/minecraft-960.webp",
    "sourceOriginal": "assets/gaming/minecraft-source.jpg",
    "width": 960,
    "height": 720,
    "source": "https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Hero-Image_Vanilla_Standard_1200x675.jpg",
    "sourcePage": "https://www.minecraft.net/en-us/store/minecraft-java-bedrock-edition-pc"
  }
];
