// Generated by build-offline.cjs.
const CACHE_NAME = 'shub-offline-6dd841885962';
const OFFLINE_ASSETS = ["/offline.html","/offline-boot.js","/assets/ui/offline-page.css","/assets/ui/offline-page.js","/assets/ui/offline-batman.js","/assets/batman/cursor.svg","/assets/fonts/inter-latin.woff2","/assets/fonts/lilita-one-latin.woff2","/assets/brand/favicon.svg"];
/* Included in the generated /offline-sw.js; no portfolio pages or media are cached. */
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE_NAME);
    await cache.addAll(OFFLINE_ASSETS.map(url => new Request(url, { cache: 'reload' })));
    await self.skipWaiting();
  })());
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith('shub-offline-') && name !== CACHE_NAME).map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', event => {
  const request = event.request;
  const url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const controller = new AbortController();
      const timeout = setTimeout(() => controller.abort(), 6000);
      try {
        return await fetch(request, { signal: controller.signal });
      } catch {
        const cache = await caches.open(CACHE_NAME);
        const page = await cache.match('/offline.html');
        return page || Response.error();
      } finally { clearTimeout(timeout); }
    })());
  } else if (OFFLINE_ASSETS.includes(url.pathname)) {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE_NAME);
      return await cache.match(url.pathname) || fetch(request);
    })());
  }
});
